### ISSUE TITLE
[bug] camera stops streaming without timeout

### ISSUE THREAD

**Issue by Yang-Xijie** [Edgenesis/shifu#202]
In `examples/rtspDeviceShifu/camera-deployment/deviceshifu-camera-configmap.yaml`:

```yaml
    instructionSettings:
      defaultTimeoutSeconds: 0
```

should be added or the camera will stop streaming after the default 4 seconds.

Supplement:

```yaml
data:
  driverProperties: |
    driverSku: HikVision
    driverImage: edgenesis/camera-python:v0.0.1-1
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: 0
    instructions:
      capture:
      info:
      stream:
      move/up:
      move/down:
      move/left:
      move/right:
```
