### ISSUE TITLE
In deviceShifuBase feature, convert it from single EdgeDevice to a list type of EdgeDevice

### ISSUE THREAD

**Issue by kris21he** [Edgenesis/shifu#538]
Change EdgeDevice type from single type to array type, only support first item of config so not breaking current behavior.

Accept criteria:

1. in examples/httpDeviceShifu/deployment/http-edgedevice.yaml, let's config as following
```
spec:
  -sku: "device1"
    connection: Ethernet
    address: 192.168.11.16:12345
    protocol: HTTP
```
2. after this change, make shifu still working with following command
```
kubectl apply -f examples/httpDeviceShifu/deployment
```

3. if there are multiple edgedevices in http_edgedevice.yaml file, always use the first one and ignore others
